-- PostgreSQL/Supabase-compatible schema converted from DB.sql
-- Note: Supabase already provides a database; do not CREATE DATABASE/USE.

CREATE TABLE IF NOT EXISTS enemies (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT NULL,
	creature_type VARCHAR(100) NULL,
	challenge_rating VARCHAR(50) NULL,
	source VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT uq_enemies_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS attributes (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(10) NOT NULL,
	name VARCHAR(100) NOT NULL,
	description TEXT NULL,
	CONSTRAINT uq_attributes_code UNIQUE (code),
	CONSTRAINT uq_attributes_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS enemy_attributes (
	enemy_id INT NOT NULL,
	attribute_id INT NOT NULL,
	value INT NOT NULL,
	PRIMARY KEY (enemy_id, attribute_id),
	CONSTRAINT fk_enemy_attributes_enemy
		FOREIGN KEY (enemy_id) REFERENCES enemies (id)
		ON DELETE CASCADE,
	CONSTRAINT fk_enemy_attributes_attribute
		FOREIGN KEY (attribute_id) REFERENCES attributes (id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS weapons (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	weapon_type VARCHAR(50) NOT NULL,
	combat_technique VARCHAR(100) NULL,
	damage_dice_count INT NULL,
	damage_dice_sides INT NULL,
	damage_bonus INT NULL,
	attack_mod INT NULL,
	parry_mod INT NULL,
	range_distance VARCHAR(50) NULL,
	initiative_mod INT NULL,
	load_value INT NULL,
	weight DECIMAL(6,2) NULL,
	price DECIMAL(10,2) NULL,
	hands_required BOOLEAN NOT NULL DEFAULT TRUE,
	is_ranged BOOLEAN NOT NULL DEFAULT FALSE,
	special_rules TEXT NULL,
	source VARCHAR(255) NULL,
	CONSTRAINT uq_weapons_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS enemy_weapons (
	enemy_id INT NOT NULL,
	weapon_id INT NOT NULL,
	is_primary BOOLEAN NOT NULL DEFAULT FALSE,
	notes TEXT NULL,
	PRIMARY KEY (enemy_id, weapon_id),
	CONSTRAINT fk_enemy_weapons_enemy
		FOREIGN KEY (enemy_id) REFERENCES enemies (id)
		ON DELETE CASCADE,
	CONSTRAINT fk_enemy_weapons_weapon
		FOREIGN KEY (weapon_id) REFERENCES weapons (id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS advantages (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	category VARCHAR(100) NULL,
	ap_cost INT NULL,
	description TEXT NULL,
	source VARCHAR(255) NULL,
	CONSTRAINT uq_advantages_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS disadvantages (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	category VARCHAR(100) NULL,
	ap_cost INT NULL,
	description TEXT NULL,
	source VARCHAR(255) NULL,
	CONSTRAINT uq_disadvantages_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS special_abilities (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	category VARCHAR(100) NULL,
	ap_cost INT NULL,
	prerequisites TEXT NULL,
	description TEXT NULL,
	source VARCHAR(255) NULL,
	CONSTRAINT uq_special_abilities_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS enemy_advantages (
	enemy_id INT NOT NULL,
	advantage_id INT NOT NULL,
	notes TEXT NULL,
	PRIMARY KEY (enemy_id, advantage_id),
	CONSTRAINT fk_enemy_advantages_enemy
		FOREIGN KEY (enemy_id) REFERENCES enemies (id)
		ON DELETE CASCADE,
	CONSTRAINT fk_enemy_advantages_advantage
		FOREIGN KEY (advantage_id) REFERENCES advantages (id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS enemy_disadvantages (
	enemy_id INT NOT NULL,
	disadvantage_id INT NOT NULL,
	notes TEXT NULL,
	PRIMARY KEY (enemy_id, disadvantage_id),
	CONSTRAINT fk_enemy_disadvantages_enemy
		FOREIGN KEY (enemy_id) REFERENCES enemies (id)
		ON DELETE CASCADE,
	CONSTRAINT fk_enemy_disadvantages_disadvantage
		FOREIGN KEY (disadvantage_id) REFERENCES disadvantages (id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS enemy_special_abilities (
	enemy_id INT NOT NULL,
	special_ability_id INT NOT NULL,
	notes TEXT NULL,
	PRIMARY KEY (enemy_id, special_ability_id),
	CONSTRAINT fk_enemy_special_abilities_enemy
		FOREIGN KEY (enemy_id) REFERENCES enemies (id)
		ON DELETE CASCADE,
	CONSTRAINT fk_enemy_special_abilities_special_ability
		FOREIGN KEY (special_ability_id) REFERENCES special_abilities (id)
		ON DELETE RESTRICT
);

INSERT INTO attributes (code, name) VALUES
	('MU', 'Mut'),
	('KL', 'Klugheit'),
	('IN', 'Intuition'),
	('CH', 'Charisma'),
	('FF', 'Fingerfertigkeit'),
	('GE', 'Gewandtheit'),
	('KO', 'Konstitution'),
	('KK', 'Körperkraft'),
	('LE', 'Lebensenergie'),
	('ASP', 'Astralenergie'),
	('KAP', 'Karmaenergie'),
	('GS', 'Geschwindigkeit'),
	('INI', 'Initiative'),
	('AW', 'Ausweichen')
ON CONFLICT (code) DO NOTHING;

-- Optional: keep updated_at in sync on updates
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enemies_updated_at ON enemies;
CREATE TRIGGER trg_enemies_updated_at
BEFORE UPDATE ON enemies
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
